/*
	To be run as CMS_MTD_TMING_COND
*/

DROP TABLE CMS_MTD_TMING_COND.TEMPLATE_NAME CASCADE CONSTRAINTS;

CREATE TABLE CMS_MTD_TMING_COND.TEMPLATE_NAME
(
  RECORD_ID                NUMBER(38)	NOT NULL,
  CONDITION_DATA_SET_ID	   NUMBER(38)	NOT NULL,
  TEMPLATE_COLUMNS
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE UNIQUE INDEX CMS_MTD_TMING_COND.TEMPLATE_SHRTNAME_PK ON CMS_MTD_TMING_COND.TEMPLATE_NAME (RECORD_ID);

ALTER TABLE CMS_MTD_TMING_COND.TEMPLATE_NAME ADD (
  CONSTRAINT TEMPLATE_SHRTNAME_PK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX CMS_MTD_TMING_COND.TEMPLATE_SHRTNAME_PK
  ENABLE VALIDATE);


CREATE INDEX CMS_MTD_TMING_COND.TEMPLATE_SHRTNAME_FK_I ON CMS_MTD_TMING_COND.TEMPLATE_NAME (CONDITION_DATA_SET_ID);

ALTER TABLE CMS_MTD_TMING_COND.TEMPLATE_NAME ADD (
  CONSTRAINT TEMPLATE_SHRTNAME_FK 
  FOREIGN KEY (CONDITION_DATA_SET_ID) 
  REFERENCES CMS_MTD_CORE_COND.COND_DATA_SETS (CONDITION_DATA_SET_ID)
  ENABLE VALIDATE);

GRANT SELECT ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO CMS_MTD_TMING_CONDITION_READER;

GRANT SELECT ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO PUBLIC;

GRANT INSERT ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT UPDATE ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT INSERT ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO CMS_MTD_PRTYP_TMING_WRT;
GRANT UPDATE ON CMS_MTD_TMING_COND.TEMPLATE_NAME TO CMS_MTD_PRTYP_TMING_WRT;
