


/*
        To be run as CMS_MTD_CORE_COND
*/

INSERT INTO CMS_MTD_CORE_COND.KINDS_OF_CONDITIONS (NAME, IS_RECORD_DELETED, EXTENSION_TABLE_NAME, COMMENT_DESCRIPTION) VALUES ('SENSOR MODULE CH QCQA', 'F', 'SENSOR_MODULE_CH_QCQA', 'Data collected during QCQA of SensorModules');
/*
	To be run as CMS_MTD_TMING_COND
*/

DROP TABLE CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA CASCADE CONSTRAINTS;

CREATE TABLE CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA
(
  RECORD_ID                NUMBER(38)	NOT NULL,
  CONDITION_DATA_SET_ID	   NUMBER(38)	NOT NULL,
  CHANNEL	INT CONSTRAINT SM_CH_CHANNEL CHECK (CHANNEL >= 0 AND CHANNEL <= 15),
  CHLOLEFT	NUMBER	NOT NULL,
  CHWIDTHLEFT	NUMBER	NOT NULL,
  CHLORIGHT	NUMBER	NOT NULL,
  CHWIDTHRIGHT	NUMBER	NOT NULL,
  BARLO		NUMBER	NOT NULL,
  BARWIDTH	NUMBER	NOT NULL
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE UNIQUE INDEX CMS_MTD_TMING_COND.SNSR_MDL_CH_QCQ_PK ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA (RECORD_ID);

ALTER TABLE CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA ADD (
  CONSTRAINT SNSR_MDL_CH_QCQ_PK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX CMS_MTD_TMING_COND.SNSR_MDL_CH_QCQ_PK
  ENABLE VALIDATE);


CREATE INDEX CMS_MTD_TMING_COND.SNSR_MDL_CH_QCQ_FK_I ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA (CONDITION_DATA_SET_ID);

ALTER TABLE CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA ADD (
  CONSTRAINT SNSR_MDL_CH_QCQ_FK 
  FOREIGN KEY (CONDITION_DATA_SET_ID) 
  REFERENCES CMS_MTD_CORE_COND.COND_DATA_SETS (CONDITION_DATA_SET_ID)
  ENABLE VALIDATE);

GRANT SELECT ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO CMS_MTD_TMING_CONDITION_READER;

GRANT SELECT ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO PUBLIC;

GRANT INSERT ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT UPDATE ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT INSERT ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO CMS_MTD_PRTYP_TMING_WRT;
GRANT UPDATE ON CMS_MTD_TMING_COND.SENSOR_MODULE_CH_QCQA TO CMS_MTD_PRTYP_TMING_WRT;

INSERT INTO CMS_MTD_CORE_COND.COND_TO_PART_RLTNSHPS
  (KIND_OF_PART_ID, KIND_OF_CONDITION_ID, DISPLAY_NAME, IS_RECORD_DELETED)
  VALUES ((SELECT KIND_OF_PART_ID FROM CMS_MTD_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE
           DISPLAY_NAME = 'SensorModule' AND IS_RECORD_DELETED = 'F'),
           (SELECT KIND_OF_CONDITION_ID FROM
           CMS_MTD_CORE_COND.KINDS_OF_CONDITIONS WHERE EXTENSION_TABLE_NAME = 'SENSOR_MODULE_CH_QCQA' AND 
           NAME = 'SENSOR MODULE CH QCQA'), 'Data collected during QCQA of SensorModules for SensorModule', 'F'); 
