


/*
        To be run as CMS_MTD_CORE_COND
*/

INSERT INTO CMS_MTD_CORE_COND.KINDS_OF_CONDITIONS (NAME, IS_RECORD_DELETED, EXTENSION_TABLE_NAME, COMMENT_DESCRIPTION) VALUES ('LY MEASUREMENT', 'F', 'LY_MEASUREMENT', 'Light Yield measurements\nB_RMS: average RMS of the baseline before PMT signal\nB_xS_ASYM: asymmetry of the RMS distribution at x sigma\nLY_ABS: absolute light yield in pe/MeV\nLY_NORM: light yield relative to reference crystal\nDECAY_TIME: decay time in ns');
/*
	To be run as CMS_MTD_TMING_COND
*/

DROP TABLE CMS_MTD_TMING_COND.LY_MEASUREMENT CASCADE CONSTRAINTS;

CREATE TABLE CMS_MTD_TMING_COND.LY_MEASUREMENT
(
  RECORD_ID                NUMBER(38)	NOT NULL,
  CONDITION_DATA_SET_ID	   NUMBER(38)	NOT NULL,
  B_RMS	NUMBER	NOT NULL,
  B_3S_ASYM	NUMBER	NOT NULL,
  B_2S_ASYM	NUMBER	NOT NULL,
  LY_ABS	NUMBER	NOT NULL,
  LY_NORM	NUMBER	NOT NULL,
  DECAY_TIME	NUMBER	NOT NULL
)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

CREATE UNIQUE INDEX CMS_MTD_TMING_COND.LY_MSRMNT_PK ON CMS_MTD_TMING_COND.LY_MEASUREMENT (RECORD_ID);

ALTER TABLE CMS_MTD_TMING_COND.LY_MEASUREMENT ADD (
  CONSTRAINT LY_MSRMNT_PK
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX CMS_MTD_TMING_COND.LY_MSRMNT_PK
  ENABLE VALIDATE);


CREATE INDEX CMS_MTD_TMING_COND.LY_MSRMNT_FK_I ON CMS_MTD_TMING_COND.LY_MEASUREMENT (CONDITION_DATA_SET_ID);

ALTER TABLE CMS_MTD_TMING_COND.LY_MEASUREMENT ADD (
  CONSTRAINT LY_MSRMNT_FK 
  FOREIGN KEY (CONDITION_DATA_SET_ID) 
  REFERENCES CMS_MTD_CORE_COND.COND_DATA_SETS (CONDITION_DATA_SET_ID)
  ENABLE VALIDATE);

GRANT SELECT ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO CMS_MTD_TMING_CONDITION_READER;

GRANT SELECT ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO PUBLIC;

INSERT INTO CMS_MTD_CORE_COND.COND_TO_PART_RLTNSHPS
  (KIND_OF_PART_ID, KIND_OF_CONDITION_ID, DISPLAY_NAME, IS_RECORD_DELETED)
  VALUES ((SELECT KIND_OF_PART_ID FROM CMS_MTD_CORE_CONSTRUCT.KINDS_OF_PARTS WHERE
           DISPLAY_NAME = 'singleBarCrystal' AND IS_RECORD_DELETED = 'F'),
	   (SELECT KIND_OF_CONDITION_ID FROM
	   CMS_MTD_CORE_COND.KINDS_OF_CONDITIONS WHERE EXTENSION_TABLE_NAME = 'LY_MEASUREMENT' AND
	   NAME = 'LY MEASUREMENT'), 'LY MEASUREMENT for singleBarCrystal', 'F'); 

GRANT INSERT ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT UPDATE ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO CMS_MTD_CORE_CONDITION_WRITER;
GRANT INSERT ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO CMS_MTD_PRTYP_TMING_WRT;
GRANT UPDATE ON CMS_MTD_TMING_COND.LY_MEASUREMENT TO CMS_MTD_PRTYP_TMING_WRT;
