SELECT BARCODE FROM CMS_MTD_CORE_CONSTRUCT.PARTS
WHERE BARCODE NOT IN (SELECT P.BARCODE FROM CMS_MTD_CORE_CONSTRUCT.PARTS P
      	      	      JOIN CMS_MTD_CORE_COND.COND_DATA_SETS DS ON (DS.PART_ID = P.PART_ID
		      AND DS.KIND_OF_CONDITION_ID = 2600))
	      AND BARCODE NOT LIKE '%-%'
	      AND KIND_OF_PART_ID IN (3020, 3040, 3060, 4, 5, 6) ORDER BY BARCODE;
