/*
set linesize 112

COLUMN BATCH_NUMBER FORMAT A12
COLUMN BARCODE FORMAT A18
COLUMN DISPLAY_NAME FORMAT A18
COLUMN LOCATION_NAME FORMAT A8
COLUMN MANUFACTURER_NAME FORMAT A12
COLUMN BATCH_INGOT_DATA FORMAT A16
COLUMN OPERATORCOMMENT FORMAT A16
*/

CREATE VIEW PARTSVIEW AS
SELECT P.BARCODE, P.BATCH_NUMBER, K.DISPLAY_NAME, L.LOCATION_NAME, MA.MANUFACTURER_NAME,
       X.BATCH_INGOT_DATA, X.OPERATORCOMMENT
        FROM CMS_MTD_CORE_CONSTRUCT.PARTS P 
       	JOIN CMS_MTD_CORE_CONSTRUCT.KINDS_OF_PARTS K 
	ON K.KIND_OF_PART_ID = P.KIND_OF_PART_ID 
	JOIN CMS_MTD_CORE_MANAGEMNT.LOCATIONS L
	ON P.LOCATION_ID = L.LOCATION_ID
	JOIN CMS_MTD_CORE_CONSTRUCT.MANUFACTURERS MA
	ON MA.MANUFACTURER_ID = P.MANUFACTURER_ID
 	LEFT JOIN CMS_MTD_CORE_COND.COND_DATA_SETS CDS
	ON CDS.PART_ID = P.PART_ID
        LEFT JOIN CMS_MTD_TMING_COND.XTALREGISTRATION X
	ON X.CONDITION_DATA_SET_ID = CDS.CONDITION_DATA_SET_ID
	WHERE P.IS_RECORD_DELETED = 'F'
	ORDER BY K.DISPLAY_NAME, P.BARCODE;
